namespace ApisConsulta.Application.Payments.Response;

/// <summary>
/// A payment as it was persisted in BambooERP (<c>Payments</c>), re-read after the insert
/// so it carries the folio generated by the database.
/// </summary>
public class PaymentResponse
{
    public int PaymentId { get; set; }

    /// <summary>Folio generated by the database. Example: <c>PAY-0826-000022</c>.</summary>
    public string? Folio { get; set; }

    public string? CustomerCode { get; set; }
    public string? Customer { get; set; }
    public DateTime? PaymentDate { get; set; }

    /// <summary>Amount registered. Null while the payment has not been validated.</summary>
    public decimal? Amount { get; set; }

    public int PaymentFormId { get; set; }

    /// <summary>SAT code of the payment form (<c>sat_FormaPago.vchCode</c>). Example: <c>03</c>.</summary>
    public string? PaymentFormCode { get; set; }

    public string? PaymentForm { get; set; }

    /// <summary>Receiving company (<c>origen_cuenta</c>), derived from the bank account.</summary>
    public int AccountId { get; set; }

    public string? Account { get; set; }

    public int BankId { get; set; }
    public string? Bank { get; set; }
    public string? BankAccountNumber { get; set; }

    public int StatusId { get; set; }

    /// <summary>Status as stored in BambooERP (<c>catEstatus</c>, in Spanish).</summary>
    public string? StatusRaw { get; set; }

    /// <summary>VALID, REJECTED, PENDING, IN_PROCESS, CANCELLED or UNKNOWN.</summary>
    public string? Status { get; set; }

    public string? Reference { get; set; }
    public string? PaymentType { get; set; }

    /// <summary>Sale the payment was related to, when <c>saleFolio</c> was sent.</summary>
    public int? SaleId { get; set; }

    public string? SaleFolio { get; set; }

    public int DepartmentId { get; set; }
    public string? Department { get; set; }

    public int UploadedById { get; set; }
    public int? SellerId { get; set; }
    public string? PaymentFilePath { get; set; }
    public string? Comentary { get; set; }
    public string? Observations { get; set; }
    public DateTime? CreatedAt { get; set; }
}
