using System.ComponentModel.DataAnnotations;

namespace ApisConsulta.Application.Payments.Requests;

/// <summary>
/// Payment to register in BambooERP (<c>Payments</c>). It reproduces what the ERP does
/// today when a voucher is uploaded: the row is created pending validation and its folio
/// is generated by the database.
/// </summary>
public class CreatePaymentRequest
{
    /// <summary>Customer the payment belongs to (<c>customers.customer_code</c>).</summary>
    [Required(ErrorMessage = "customerCode is required.")]
    [MaxLength(50)]
    public string CustomerCode { get; set; } = string.Empty;

    /// <summary>Date the payment was made. Defaults to today when omitted.</summary>
    public DateTime? PaymentDate { get; set; }

    /// <summary>
    /// Bank account the money was deposited into (<c>bancos.id</c>). The receiving company
    /// (<c>Payments.AccountId</c>) is derived from it.
    /// </summary>
    [Range(1, int.MaxValue, ErrorMessage = "bankId is required.")]
    public int BankId { get; set; }

    /// <summary>Payment form (<c>sat_FormaPago.ID</c>). Example: 3 = transferencia.</summary>
    [Range(1, int.MaxValue, ErrorMessage = "paymentFormId is required.")]
    public int PaymentFormId { get; set; }

    /// <summary>
    /// Amount of the payment. Optional: the ERP leaves it empty until the payment is
    /// validated, so it may be sent later.
    /// </summary>
    [Range(0.01, double.MaxValue, ErrorMessage = "amount must be greater than zero.")]
    public decimal? Amount { get; set; }

    /// <summary>Bank reference of the transfer/deposit.</summary>
    [MaxLength(250)]
    public string? Reference { get; set; }

    /// <summary><c>payment</c> (default), <c>credit</c> or <c>advance</c>.</summary>
    [MaxLength(100)]
    public string? PaymentType { get; set; }

    [MaxLength(1500)]
    public string? Comentary { get; set; }

    [MaxLength(500)]
    public string? Observations { get; set; }

    /// <summary>Path of the uploaded voucher file (<c>Payments.PaymentFilePath</c>).</summary>
    [MaxLength(250)]
    public string? PaymentFilePath { get; set; }

    /// <summary>
    /// Folio of the sale the payment is applied to (<c>quotation.billCode</c>). When sent,
    /// the database relates the payment to the sale and moves that sale to status 29.
    /// </summary>
    [MaxLength(100)]
    public string? SaleFolio { get; set; }

    /// <summary>User registering the payment (<c>catUsers.idUsuario</c>).</summary>
    [Range(1, int.MaxValue, ErrorMessage = "uploadedById is required.")]
    public int UploadedById { get; set; }

    /// <summary>Salesperson the payment is credited to (<c>catUsers.idUsuario</c>).</summary>
    public int? SellerId { get; set; }

    /// <summary>
    /// Branch/department the payment belongs to (<c>departments.id</c>). Defaults to the
    /// branch of the user in <see cref="UploadedById"/>.
    /// </summary>
    public int? DepartmentId { get; set; }

    /// <summary>
    /// Status the payment is created with (<c>catEstatus.idEstatus</c>). Defaults to 4
    /// (PENDIENTE), which is how the ERP registers a payment awaiting validation.
    /// </summary>
    public int? StatusId { get; set; }

    // ---------------------------------------------------------------------------------
    // Kingdee fields. Every one of them is optional so the payload the ERP already sends
    // keeps working. They are Kingdee's own identifiers: BambooERP has no catalog to
    // validate them against, so they are stored exactly as they arrive.
    //
    // The rest of the Kingdee document is derived from what the payment already carries
    // and must not be sent: FDate, FBranchID, FSalerID, FCustomerID, FNote and
    // FReceiveAmt. See PaymentResponse.Kingdee.
    // ---------------------------------------------------------------------------------

    /// <summary>
    /// <c>FBillNo</c> (单据编号): document number in Kingdee. It does not replace
    /// <c>folio</c>, which the database keeps generating on its own.
    /// </summary>
    [MaxLength(100)]
    public string? KingdeeBillNo { get; set; }

    /// <summary><c>FBizOrgId</c> (业务组织).</summary>
    public int? BizOrgId { get; set; }

    /// <summary><c>FBizOrg</c>.</summary>
    [MaxLength(50)]
    public string? BizOrgCode { get; set; }

    /// <summary><c>FSETTLEORGID</c> (结算组织).</summary>
    public int? SettleOrgId { get; set; }

    /// <summary><c>FSETTLEORG</c>.</summary>
    [MaxLength(50)]
    public string? SettleOrgCode { get; set; }

    /// <summary>
    /// <c>FCashierID</c> (收银员). The cashier in Kingdee, which is not necessarily
    /// <see cref="UploadedById"/> — that one is the Bamboo user uploading the voucher.
    /// </summary>
    public int? CashierId { get; set; }

    /// <summary><c>FCashier</c>.</summary>
    [MaxLength(50)]
    public string? CashierCode { get; set; }

    /// <summary>
    /// <c>FAccountID</c> (账户). Kingdee's account; unrelated to <c>accountId</c> in the
    /// response, which is the receiving company derived from <see cref="BankId"/>.
    /// </summary>
    public int? KingdeeAccountId { get; set; }

    /// <summary><c>FAccount</c>.</summary>
    [MaxLength(50)]
    public string? KingdeeAccountCode { get; set; }

    /// <summary>
    /// <c>FReceiveTypeID</c> (收款方式). Kingdee's receipt method, independent from
    /// <see cref="PaymentFormId"/> (the SAT payment form).
    /// </summary>
    public int? ReceiveTypeId { get; set; }

    /// <summary><c>FReceiveType</c>.</summary>
    [MaxLength(50)]
    public string? ReceiveTypeCode { get; set; }

    /// <summary><c>FSETTLECURRENCYID</c> (结算币别).</summary>
    public int? SettleCurrencyId { get; set; }

    /// <summary><c>FSETTLECURRENCY</c>. Example: <c>MXN</c>.</summary>
    [MaxLength(10)]
    public string? SettleCurrencyCode { get; set; }

    /// <summary><c>FReceiveCurrencyID</c> (收款币别).</summary>
    public int? ReceiveCurrencyId { get; set; }

    /// <summary>
    /// <c>FReceiveCurrency</c>. Defaults to <see cref="SettleCurrencyCode"/> when omitted.
    /// </summary>
    [MaxLength(10)]
    public string? ReceiveCurrencyCode { get; set; }

    /// <summary>
    /// <c>FExchangeRate</c> (汇率). Defaults to 1 when both currencies are the same.
    /// </summary>
    [Range(0.000001, double.MaxValue, ErrorMessage = "exchangeRate must be greater than zero.")]
    public decimal? ExchangeRate { get; set; }

    /// <summary><c>FCardID</c> (卡号).</summary>
    public int? CardId { get; set; }

    /// <summary><c>FCard</c>.</summary>
    [MaxLength(50)]
    public string? CardNumber { get; set; }

    /// <summary><c>FMemberID</c> (会员卡号).</summary>
    public int? MemberId { get; set; }

    /// <summary><c>FMember</c>.</summary>
    [MaxLength(50)]
    public string? MemberCardNumber { get; set; }

    /// <summary>
    /// <c>FRechargeAmount</c> (充值金额): amount credited to the card. It is not
    /// <see cref="Amount"/> (<c>FReceiveAmt</c>), which is what was actually collected.
    /// </summary>
    [Range(0.01, double.MaxValue, ErrorMessage = "rechargeAmount must be greater than zero.")]
    public decimal? RechargeAmount { get; set; }
}
