using System.ComponentModel.DataAnnotations;

namespace ApisConsulta.Application.Payments.Requests;

/// <summary>
/// Payment to register in BambooERP (<c>Payments</c>). It reproduces what the ERP does
/// today when a voucher is uploaded: the row is created pending validation and its folio
/// is generated by the database.
/// </summary>
public class CreatePaymentRequest
{
    /// <summary>Customer the payment belongs to (<c>customers.customer_code</c>).</summary>
    [Required(ErrorMessage = "customerCode is required.")]
    [MaxLength(50)]
    public string CustomerCode { get; set; } = string.Empty;

    /// <summary>Date the payment was made. Defaults to today when omitted.</summary>
    public DateTime? PaymentDate { get; set; }

    /// <summary>
    /// Bank account the money was deposited into (<c>bancos.id</c>). The receiving company
    /// (<c>Payments.AccountId</c>) is derived from it.
    /// </summary>
    [Range(1, int.MaxValue, ErrorMessage = "bankId is required.")]
    public int BankId { get; set; }

    /// <summary>Payment form (<c>sat_FormaPago.ID</c>). Example: 3 = transferencia.</summary>
    [Range(1, int.MaxValue, ErrorMessage = "paymentFormId is required.")]
    public int PaymentFormId { get; set; }

    /// <summary>
    /// Amount of the payment. Optional: the ERP leaves it empty until the payment is
    /// validated, so it may be sent later.
    /// </summary>
    [Range(0.01, double.MaxValue, ErrorMessage = "amount must be greater than zero.")]
    public decimal? Amount { get; set; }

    /// <summary>Bank reference of the transfer/deposit.</summary>
    [MaxLength(250)]
    public string? Reference { get; set; }

    /// <summary><c>payment</c> (default), <c>credit</c> or <c>advance</c>.</summary>
    [MaxLength(100)]
    public string? PaymentType { get; set; }

    [MaxLength(1500)]
    public string? Comentary { get; set; }

    [MaxLength(500)]
    public string? Observations { get; set; }

    /// <summary>Path of the uploaded voucher file (<c>Payments.PaymentFilePath</c>).</summary>
    [MaxLength(250)]
    public string? PaymentFilePath { get; set; }

    /// <summary>
    /// Folio of the sale the payment is applied to (<c>quotation.billCode</c>). When sent,
    /// the database relates the payment to the sale and moves that sale to status 29.
    /// </summary>
    [MaxLength(100)]
    public string? SaleFolio { get; set; }

    /// <summary>User registering the payment (<c>catUsers.idUsuario</c>).</summary>
    [Range(1, int.MaxValue, ErrorMessage = "uploadedById is required.")]
    public int UploadedById { get; set; }

    /// <summary>Salesperson the payment is credited to (<c>catUsers.idUsuario</c>).</summary>
    public int? SellerId { get; set; }

    /// <summary>
    /// Branch/department the payment belongs to (<c>departments.id</c>). Defaults to the
    /// branch of the user in <see cref="UploadedById"/>.
    /// </summary>
    public int? DepartmentId { get; set; }

    /// <summary>
    /// Status the payment is created with (<c>catEstatus.idEstatus</c>). Defaults to 4
    /// (PENDIENTE), which is how the ERP registers a payment awaiting validation.
    /// </summary>
    public int? StatusId { get; set; }
}
